# -*- mode: ruby -*-
# vi: set ft=ruby :

# Required plugins
required_plugins = %w(
    vagrant-host-shell
    vagrant-sshfs
    vagrant-vbguest
    )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

# !!! IMPORTANT !!!
# If host machine has sufficient memory and CPUs use these values, otherwise reduce accordingly to not cripple the host machine.
# If adjusting here, ensure that the command line to start the installer build is adjusted for memory and CPUs as well.
MEM = 8192
CPU = 4

# Environment Profiles - currently only 
PROFILE = ENV['PROFILE'] || 'x86_64'

VAGRANTFILE_API_VERSION = '2'
#
#  Fully documented Vagrantfile available
#  in the wiki:  https://github.com/josenk/vagrant-vmware-esxi/wiki
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# map external folders
    config.vm.synced_folder "./", "/vagrant"
    config.vm.synced_folder "../", "/home/vagrant/rockstor-installer"

     config.vm.define "rockstor-installer" do |v|
        v.vm.hostname = "rockstor-installer"
        if PROFILE == "x86_64" then
            # One can switch back to bento in case OpenSUSE is broken (typically issues around VB guest additions
            # https://portal.cloud.hashicorp.com/vagrant/discover?query=opensuse
            v.vm.box = 'opensuse/Leap-15.6.x86_64'
		    # if a specific version should be used:
			# v.vm.box_version = '15.6.13.356'
        else
            # https://portal.cloud.hashicorp.com/vagrant/discover?architectures=arm64&query=opensuse
            v.vm.box = 'bento/opensuse-leap-15.6'
        end

        # Provider specific variables
        v.vm.provider :virtualbox do |vb|
            vb.memory = MEM
            vb.cpus = CPU
			# Enable nested VMs, so kiwi box-build can be used
			vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
        end

        if PROFILE == "x86_64" then
            config.vm.provision "shell", inline: <<-SHELL
			# install KVM and KVM tools for virtual machine within VM & python dev tools
				sudo zypper -n install -t pattern kvm_server kvm_tools
				sudo zypper -n install git python3-devel gcc
			# create virtual python environment
				python3 -m venv kiwi-env
			# update pip if necessary
				sudo ./kiwi-env/bin/python3 -m pip install --upgrade pip
			# install kiwi and kiwi box plugin
				./kiwi-env/bin/pip3 install kiwi kiwi-boxed-plugin
			# copy build script from local to VM
				sudo cp ./rockstor-installer/vagrant_env/run_kiwi.sh ./
			# make build script executable
				sudo chmod u+x run_kiwi.sh
        SHELL
		end
    end
end
